"""Add image field to Ticket

Revision ID: 0bd35de4d198
Revises: 64b5c62f54bb
Create Date: 2026-05-06 17:08:17.468833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd35de4d198'
down_revision = '64b5c62f54bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_adjunta', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('imagen_adjunta')

    # ### end Alembic commands ###
