"""add telefono to psicologo

Revision ID: 10501e100b07
Revises: 98b831b53e31
Create Date: 2026-01-20 22:57:50.930040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10501e100b07'
down_revision = '98b831b53e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
