"""Make paciente fields required

Revision ID: 25d00046401d
Revises: 51e5aa207d57
Create Date: 2026-01-20 10:39:09.091574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25d00046401d'
down_revision = '51e5aa207d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('dni_nif',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('dni_nif',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
