"""refactor_chat_to_phone_and_add_appointment_fields

Revision ID: 29862f56de33
Revises: c8d81ba88136
Create Date: 2026-02-02 21:29:19.637633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29862f56de33'
down_revision = 'c8d81ba88136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_especialidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motivo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('es_primera_vez', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'especialidades', ['id_especialidad'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('es_primera_vez')
        batch_op.drop_column('motivo')
        batch_op.drop_column('id_especialidad')

    # ### end Alembic commands ###
