"""add_precio_urgencia_to_psicologo

Revision ID: 312695068b5f
Revises: 93d9214fd848
Create Date: 2026-02-02 21:42:57.059979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312695068b5f'
down_revision = '93d9214fd848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_urgencia', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_column('precio_urgencia')

    # ### end Alembic commands ###
