"""add google meet fields retry

Revision ID: 47abb1dee0f5
Revises: 10501e100b07
Create Date: 2026-01-21 09:58:25.023562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47abb1dee0f5'
down_revision = '10501e100b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enlace_meet', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')
        batch_op.drop_column('enlace_meet')

    # ### end Alembic commands ###
