"""Sync models and add admin retry

Revision ID: 51e5aa207d57
Revises: 800d15796ded
Create Date: 2026-01-20 10:04:03.897960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51e5aa207d57'
down_revision = '800d15796ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologo_especialidad', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('psicologo_especialidad_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('psicologo_especialidad_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'especialidades', ['especialidad_id'], ['id'])
        batch_op.create_foreign_key(None, 'psicologos', ['psicologo_id'], ['id_psicologo'])
        batch_op.drop_column('id_psicologo')
        batch_op.drop_column('id_especialidad')

    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_electronico', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('contrasena_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dni_nif', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('direccion_fiscal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero_colegiado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('foto_psicologo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cuenta_bancaria', sa.String(length=50), nullable=True))
        batch_op.alter_column('precio_presencial',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('precio_online',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('precio_chat',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_unique_constraint(None, ['correo_electronico'])
        batch_op.drop_constraint(batch_op.f('psicologos_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('verificado')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('especialidad_id')
        batch_op.drop_column('telefono')
        batch_op.drop_column('numero_cuenta')
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('numero_cuenta', mysql.VARCHAR(length=34), nullable=True))
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('especialidad_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', mysql.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('verificado', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('psicologos_ibfk_1'), 'especialidades', ['especialidad_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('precio_chat',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('precio_online',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('precio_presencial',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('cuenta_bancaria')
        batch_op.drop_column('foto_psicologo')
        batch_op.drop_column('numero_colegiado')
        batch_op.drop_column('direccion_fiscal')
        batch_op.drop_column('dni_nif')
        batch_op.drop_column('apellido')
        batch_op.drop_column('contrasena_hash')
        batch_op.drop_column('correo_electronico')

    with op.batch_alter_table('psicologo_especialidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_especialidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_psicologo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('psicologo_especialidad_ibfk_2'), 'psicologos', ['id_psicologo'], ['id_psicologo'])
        batch_op.create_foreign_key(batch_op.f('psicologo_especialidad_ibfk_1'), 'especialidades', ['id_especialidad'], ['id'])

    # ### end Alembic commands ###
