"""Add Ticket model

Revision ID: 64b5c62f54bb
Revises: 9aad87dd6400
Create Date: 2026-05-06 16:59:22.447265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b5c62f54bb'
down_revision = '9aad87dd6400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_psicologo', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('respuesta_admin', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_psicologo'], ['psicologos.id_psicologo'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('biometrico_verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('documento_acreditacion', sa.Text(length=4294967295), nullable=True))
        batch_op.add_column(sa.Column('documento_dni', sa.Text(length=4294967295), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_column('documento_dni')
        batch_op.drop_column('documento_acreditacion')
        batch_op.drop_column('biometrico_verificado')
        batch_op.drop_column('ocr_verificado')

    op.drop_table('tickets')
    # ### end Alembic commands ###
