"""Add fecha_nacimiento to Paciente

Revision ID: 7e6419c95921
Revises: enhanced_psychologist_profile
Create Date: 2026-01-12 16:42:40.641750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e6419c95921'
down_revision = 'enhanced_psychologist_profile'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.drop_column('monto')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_column('fecha_cita')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_cita', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('total')

    # ### end Alembic commands ###
