"""foto perfil obligatoria

Revision ID: 800d15796ded
Revises: 7e6419c95921
Create Date: 2026-01-14 19:08:47.743873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '800d15796ded'
down_revision = '7e6419c95921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=500), nullable=False))

    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.alter_column('foto_perfil',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.alter_column('foto_perfil',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
