"""Require fecha_nacimiento and edad for Paciente

Revision ID: 98b831b53e31
Revises: 25d00046401d
Create Date: 2026-01-20 10:42:16.448675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98b831b53e31'
down_revision = '25d00046401d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
