"""Migracion inicial limpia

Revision ID: 9aad87dd6400
Revises: 
Create Date: 2026-02-03 16:44:54.425177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aad87dd6400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('email')
    )
    op.create_table('anamnesis',
    sa.Column('id_anamnesis', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=True),
    sa.Column('antecedentes', sa.Text(), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_anamnesis'),
    sa.UniqueConstraint('id_paciente')
    )
    op.create_table('notas_sesion',
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('tipo_nota', sa.String(length=50), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id_nota')
    )
    op.drop_table('resenas')
    op.drop_table('historiales_clinicos')
    op.drop_table('resumenes_ingresos')
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_especialidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motivo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('es_primera_vez', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enlace_meet', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('precio_cita',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'especialidades', ['id_especialidad'], ['id'])

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cita', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_imponible', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('importe_total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('concepto', sa.String(length=255), nullable=True))
        batch_op.alter_column('fecha_emision',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'citas', ['id_cita'], ['id'])
        batch_op.drop_column('total')
        batch_op.drop_column('pagado')

    with op.batch_alter_table('informes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cita', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('titulo_informe', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('texto_informe', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('diagnostico', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tratamiento', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'citas', ['id_cita'], ['id'])
        batch_op.drop_column('contenido')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_envio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('leido', sa.Boolean(), nullable=True))
        batch_op.alter_column('mensaje',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('leida')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_electronico', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('contrasena_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('dni_nif', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('direccion_fiscal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_paciente', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('token_pago', sa.String(length=255), nullable=True))
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_index(batch_op.f('correo_electronico'))
        batch_op.create_unique_constraint(None, ['correo_electronico'])
        batch_op.drop_column('email')
        batch_op.drop_column('tipo_paciente')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('tipo_tarjeta')

    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('precio_telefono', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_urgencia', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('precio_chat')
        batch_op.drop_column('cuenta_bancaria')
        batch_op.drop_column('titular_cuenta')
        batch_op.drop_column('banco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banco', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('titular_cuenta', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cuenta_bancaria', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('precio_chat', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('precio_urgencia')
        batch_op.drop_column('precio_telefono')
        batch_op.drop_column('telefono')
        batch_op.drop_column('verificado')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_tarjeta', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', mysql.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('tipo_paciente', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('correo_electronico'), ['email'], unique=True)
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('token_pago')
        batch_op.drop_column('foto_paciente')
        batch_op.drop_column('direccion_fiscal')
        batch_op.drop_column('dni_nif')
        batch_op.drop_column('contrasena_hash')
        batch_op.drop_column('correo_electronico')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leida', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('mensaje',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('leido')
        batch_op.drop_column('fecha_envio')

    with op.batch_alter_table('informes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tratamiento')
        batch_op.drop_column('diagnostico')
        batch_op.drop_column('texto_informe')
        batch_op.drop_column('titulo_informe')
        batch_op.drop_column('id_cita')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fecha_emision',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('concepto')
        batch_op.drop_column('estado')
        batch_op.drop_column('importe_total')
        batch_op.drop_column('iva')
        batch_op.drop_column('base_imponible')
        batch_op.drop_column('id_cita')

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('precio_cita',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('google_calendar_event_id')
        batch_op.drop_column('enlace_meet')
        batch_op.drop_column('es_primera_vez')
        batch_op.drop_column('motivo')
        batch_op.drop_column('id_especialidad')

    op.create_table('resumenes_ingresos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('psicologo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('mes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('anio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_ingresos', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id_psicologo'], name=op.f('resumenes_ingresos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historiales_clinicos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('paciente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('contenido', mysql.TEXT(), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id_paciente'], name=op.f('historiales_clinicos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resenas',
    sa.Column('id_resena', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_psicologo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_paciente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('puntuacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comentario', mysql.TEXT(), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name=op.f('resenas_ibfk_1')),
    sa.ForeignKeyConstraint(['id_psicologo'], ['psicologos.id_psicologo'], name=op.f('resenas_ibfk_2')),
    sa.PrimaryKeyConstraint('id_resena'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('notas_sesion')
    op.drop_table('anamnesis')
    op.drop_table('administrador')
    # ### end Alembic commands ###
