"""add_stripe_session_id_to_cita

Revision ID: a1cf5efb5c4b
Revises: 312695068b5f
Create Date: 2026-02-02 23:51:09.027538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cf5efb5c4b'
down_revision = '312695068b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('stripe_session_id')

    # ### end Alembic commands ###
