"""remove_legacy_bank_details_and_sync_new_tables

Revision ID: b17afde3a2b1
Revises: a1cf5efb5c4b
Create Date: 2026-02-03 01:01:28.887206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b17afde3a2b1'
down_revision = 'a1cf5efb5c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_column('banco')
        batch_op.drop_column('titular_cuenta')
        batch_op.drop_column('cuenta_bancaria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta_bancaria', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('titular_cuenta', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('banco', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
