"""add_verificado_field_retry

Revision ID: c8d81ba88136
Revises: 47abb1dee0f5
Create Date: 2026-01-22 00:46:10.144650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d81ba88136'
down_revision = '47abb1dee0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_column('verificado')

    # ### end Alembic commands ###
