"""Initial migration

Revision ID: dbfd0e25a347
Revises: 
Create Date: 2025-12-02 18:52:17.573900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfd0e25a347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('contrasena', sa.String(length=256), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('tipo_paciente', sa.String(length=50), nullable=True),
    sa.Column('tipo_tarjeta', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('historiales_clinicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psicologos',
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('especialidad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ),
    sa.PrimaryKeyConstraint('id_psicologo'),
    sa.UniqueConstraint('email')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('tipo_cita', sa.String(length=50), nullable=True),
    sa.Column('precio_cita', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_psicologo'], ['psicologos.id_psicologo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_psicologo'], ['psicologos.id_psicologo'], ),
    sa.PrimaryKeyConstraint('id_factura'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('informes',
    sa.Column('id_informe', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_psicologo'], ['psicologos.id_psicologo'], ),
    sa.PrimaryKeyConstraint('id_informe')
    )
    op.create_table('resumenes_ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psicologo_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id_psicologo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=True),
    sa.Column('fecha_cita', sa.DateTime(), nullable=True),
    sa.Column('mensaje', sa.String(length=255), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_psicologo'], ['psicologos.id_psicologo'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('resumenes_ingresos')
    op.drop_table('informes')
    op.drop_table('facturas')
    op.drop_table('citas')
    op.drop_table('psicologos')
    op.drop_table('historiales_clinicos')
    op.drop_table('pacientes')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
